import { GoogleTagManager } from '@next/third-parties/google';
import { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Лазерне різання листових металів',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-MH74772N" />
      <body>{children}</body>
    </html>
  );
}
